openapi: 3.2.0
info:
  title: Airspace API Documentation Address Books API
  description: '# Introduction

    Airspace''s V3 API is an asynchronous RESTful API.'
  version: 3.4.2
  x-logo:
    url: https://www.airspacetechnologies.com/hubfs/Updated%20logos/Airspace%20horizontal%20logotype%20black%20and%20green%20no%20background%20011321%20(1).png
servers:
- url: https://{environment}.airspace.com/api/public/v3
  variables:
    environment:
      default: apitest
      enum:
      - api
      - apitest
tags:
- name: Address Books
  description: We support listing reusable address entries.
paths:
  /address_books:
    get:
      summary: List Address Books
      security:
      - Bearer: []
      tags:
      - Address Books
      operationId: getAddressBooks
      description: Get a list of available AddressBook items from our system
      responses:
        '200':
          description: Get a list of address books
          content:
            application/json:
              example:
                address_books:
                - id: 1
                  name: Myles Beier
                  company_id: 291
                  created_at: '2022-04-25T18:55:19.975Z'
                  updated_at: '2022-04-25T18:55:19.975Z'
                  frequent_order_id: null
                  address_id: 681
                  guid: AT4429JJ39
                  address:
                    id: 681
                    street: 509 8th Street Southeast
                    street2: Apt. 1
                    street3: null
                    city: Orange City
                    state: IA
                    zip: '51041'
                    created_at: '2022-04-26T20:24:50.138Z'
                    updated_at: '2022-04-26T20:24:50.138Z'
                    lat: '42.997673'
                    lng: '-96.052662'
                    geocoded_lat: null
                    geocoded_lng: null
                    time_zone: America/Los_Angeles
                    company: PickupsRUs
                    derived_from_airport: null
                    country: US
                    name: Myles Beier
                    special_instructions: pick it up
                    known_shipper_number: null
                    nearest_iata_code: null
                    id_check_required: false
                    id_check_verified: false
                    id_check_status: ksms_missing
                    physical_id_check_required: false
                    full_address: 509 8th Street Southeast, Apt. 1, Orange City, IA, US, 51041
                    phone:
                      id: 1466
                      country_code: '45'
                      number: '9311546931'
                      extension: '2436'
                      formatted_number: +45 9311546931, ext. 2436
                      twilio_number: '+459311546931'
                    verified_ksms_number: null
                    address_custom_attribute_values: []
                    schedule_blocks: []
                    is_hub: false
                  companies_including: []
                  company: null
                  company_name: null
                  provider_company: null
                  location_schedule_id: null
                  schedule_id: null
                  schedule: null
        '401':
          description: Authentication token is not authorized to complete the request.
          content:
            application/json:
              example:
                error: Unauthorized
components:
  securitySchemes:
    Bearer:
      description: Unique API key necessary to make API requests.
      type: http
      scheme: bearer
      name: Authorization
      in: header
