openapi: 3.2.0
info:
  title: Airspace API Documentation Labels API
  description: '# Introduction

    Airspace''s V2 API is a RESTful API.'
  version: 2.6.2
  x-logo:
    url: https://www.airspacetechnologies.com/hubfs/Updated%20logos/Airspace%20horizontal%20logotype%20black%20and%20green%20no%20background%20011321%20(1).png
servers:
- url: https://{environment}.airspace.com/api/public/v2
  variables:
    environment:
      default: apitest
      enum:
      - api
      - apitest
tags:
- name: Labels
  description: We support generating labels for Orders.
paths:
  /labels/{piece.id}.pdf:
    parameters:
    - name: piece.id
      in: path
      required: true
      description: Piece ID
      schema:
        type: string
    get:
      summary: Get a printable Airspace package label
      security:
      - Bearer: []
      tags:
      - Labels
      operationId: getLabelByPieceId
      description: Each piece should have it's own printed label. The id for each piece is in the Order object.
      responses:
        '200':
          description: The pdf is available and returned.
          content:
            application/pdf:
              example: Label.pdf
        '202':
          description: The label must be generated which can take several seconds. Please repeat the request in 15 seconds.
          content:
            application/json:
              example:
                warning: Generating the label now, try again in 15 seconds.
        '401':
          description: Authentication token is not authorized to complete the request.
          content:
            application/json:
              example:
                error: Unauthorized
        '404':
          description: The piece could not be found. Please check the id and try again.
          content:
            application/json:
              example:
                error: Not Found
components:
  securitySchemes:
    Bearer:
      description: Unique API key necessary to make API requests.
      type: http
      scheme: bearer
      name: Authorization
      in: header
